logging:
  level:
    ROOT: INFO
server:
  port: 8080

spring:
  datasource:
    username: lkjdada
    password: X1ad1221sadaY1v8UZN
    url: jdbc:postgresql://217.151.230.221:5454/xakaton?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

external:
  category-url: http://xakaton.webtm.ru/classificator/category/predict?message=
  priority-url: http://xakaton.webtm.ru/classificator/priority/predict?message=
